# Generated by Django 4.2.9 on 2024-07-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_api', '0005_remove_schoolreferralquestionset_part1_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeaklishOrder',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='UZS', max_length=3)),
                ('session_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled')], max_length=10)),
                ('organization', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCallbackUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_api.schoolprofile')),
            ],
        ),
    ]
