# Generated by Django 4.2.9 on 2024-07-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayzeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled')], max_length=10)),
                ('webhook_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
