# Generated by Django 4.2.9 on 2024-03-24 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_txt', models.TextField(blank=True, db_column='question')),
                ('voice_url', models.URLField(blank=True, db_column='voice_url', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Part-1 Question',
                'verbose_name_plural': 'Part-1 Questions',
                'db_table': 'part1_questions',
            },
        ),
        migrations.CreateModel(
            name='Part1QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Part-1 Question Category',
                'verbose_name_plural': 'Part-1 Question Categories',
                'db_table': 'part1_question_categories',
            },
        ),
        migrations.CreateModel(
            name='Part2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_txt', models.TextField(blank=True, db_column='question')),
                ('voice_url', models.URLField(blank=True, db_column='voice_url', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Part-2 Question',
                'verbose_name_plural': 'Part-2 Questions',
                'db_table': 'part2_questions',
            },
        ),
        migrations.CreateModel(
            name='Part3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_txt', models.TextField(blank=True, db_column='question_txt')),
                ('voice_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('part2_question', models.ForeignKey(db_column='part2_question_id', on_delete=django.db.models.deletion.CASCADE, to='api.part2question')),
            ],
            options={
                'verbose_name': 'Part-3 Question',
                'verbose_name_plural': 'Part-3 Questions',
                'db_table': 'part3_questions',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_column='session_id', default=uuid.uuid4, editable=False, unique=True)),
                ('result', models.TextField(blank=True, db_column='result', null=True)),
                ('part1_question', models.IntegerField(blank=True, db_column='part1_question_id', null=True)),
                ('finish_state', models.CharField(blank=True, db_column='finish_state', max_length=255, null=True)),
                ('stop_reason', models.CharField(blank=True, db_column='stop_reason', max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=255, null=True)),
                ('wait_time', models.IntegerField(blank=True, db_column='wait_time', db_comment='wait time in request in seconds', null=True)),
                ('used_tokens', models.IntegerField(blank=True, db_column='used_tokens', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Test-Session',
                'verbose_name_plural': 'Test-Sessions',
                'db_table': 'test_sessions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=255, null=True)),
                ('username', models.CharField(db_column='username', max_length=255, null=True, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, db_column='user_id')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('referral', models.CharField(blank=True, db_column='referral', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserPart3Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('tts_name', models.CharField(blank=True, db_column='tts_name', max_length=100, null=True)),
                ('answer_voice_id', models.CharField(blank=True, db_column='answer_voice_id', db_comment='voice id from from telegram voice message file_id', max_length=255, null=True)),
                ('voice_audio', models.FileField(db_column='voice_audio', null=True, upload_to='voices')),
                ('voice_length', models.IntegerField(blank=True, db_column='length', db_comment='length of answer in seconds', null=True)),
                ('tts_process_time', models.IntegerField(blank=True, db_column='tts_process_time', db_comment='wait time in request in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.ForeignKey(db_column='question_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part3_questions', related_query_name='part3_question', to='api.part3question')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_part3_results', related_query_name='user_part3_result', to='api.testsession')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': 'UserPart3Result',
                'verbose_name_plural': 'UserPart3Results',
                'db_table': 'user_part3_results',
            },
        ),
        migrations.CreateModel(
            name='UserPart2Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('voice_audio', models.FileField(db_column='voice_audio', null=True, upload_to='voices')),
                ('tts_name', models.CharField(blank=True, db_column='tts_name', max_length=100, null=True)),
                ('answer_voice_id', models.CharField(blank=True, db_column='answer_voice_id', db_comment='voice id from from telegram voice message file_id', max_length=255, null=True)),
                ('voice_length', models.IntegerField(blank=True, db_column='length', db_comment='length of answer in seconds', null=True)),
                ('tts_process_time', models.IntegerField(blank=True, db_column='tts_process_time', db_comment='wait time in request in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.ForeignKey(db_column='question_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part2_questions', related_query_name='part2_question', to='api.part2question')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_part2_results', related_query_name='user_part2_result', to='api.testsession')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': 'UserPart2Result',
                'verbose_name_plural': 'UserPart2Results',
                'db_table': 'user_part2_results',
            },
        ),
        migrations.CreateModel(
            name='UserPart1Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('tts_name', models.CharField(blank=True, db_column='tts_name', max_length=100, null=True)),
                ('voice_audio', models.FileField(db_column='voice_audio', null=True, upload_to='voices')),
                ('answer_voice_id', models.CharField(blank=True, db_column='answer_voice_id', db_comment='voice id from from telegram voice message file_id', max_length=255, null=True)),
                ('voice_length', models.IntegerField(blank=True, db_column='length', db_comment='length of answer in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='part1_questions', related_query_name='part1_question', to='api.part1question')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_part1_results', related_query_name='user_part1_result', to='api.testsession')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': 'UserPart1Result',
                'verbose_name_plural': 'UserPart1Results',
                'db_table': 'user_part1_results',
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='api.user'),
        ),
        migrations.AddField(
            model_name='part1question',
            name='question_category',
            field=models.ForeignKey(blank=True, db_column='question_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='with_category', to='api.part1questioncategory'),
        ),
    ]
