# Generated by Django 4.2.9 on 2024-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_part1question_is_active_part2question_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part1questioncategory',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
