# Generated by Django 4.2.9 on 2024-04-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.TextField()),
                ('parsed_json', models.JSONField()),
                ('feedback', models.TextField(blank=True)),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('fluency', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('vocabulary', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('grammar', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('pronunciation', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('used_topic_words', models.JSONField()),
                ('suggested_vocab', models.JSONField()),
                ('wait_time', models.FloatField(blank=True)),
                ('token_usage', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_sessions', to='school_api.testsessionschool')),
            ],
            options={
                'verbose_name': 'Parsed Session',
                'verbose_name_plural': 'Parsed Sessions',
                'db_table': 'parsed_sessions',
            },
        ),
    ]
