# Generated by Django 4.2.9 on 2024-06-01 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_part1questioncategory_is_active'),
        ('school_api', '0002_parsedsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReferralQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('part1_questions', models.ManyToManyField(related_name='referral_part1_questions', to='api.part1question')),
                ('part2_questions', models.ManyToManyField(related_name='referral_part2_questions', to='api.part2question')),
                ('part3_questions', models.ManyToManyField(related_name='referral_part3_questions', to='api.part3question')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_question_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Referral Question Set',
                'verbose_name_plural': 'School Referral Question Sets',
                'db_table': 'school_referral_question_sets',
            },
        ),
    ]
