# Generated by Django 4.2.9 on 2024-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_part1questioncategory_is_active'),
        ('school_api', '0003_schoolreferralquestionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolreferralquestionset',
            name='part1_category',
            field=models.ManyToManyField(related_name='referral_part1_categories', to='api.part1questioncategory'),
        ),
    ]
