# Generated by Django 4.2.9 on 2024-06-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0004_schoolreferralquestionset_part1_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolreferralquestionset',
            name='part1_questions',
        ),
        migrations.RemoveField(
            model_name='schoolreferralquestionset',
            name='part3_questions',
        ),
    ]
