# Generated by Django 4.2.9 on 2024-07-11 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0005_remove_schoolreferralquestionset_part1_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('score_details', models.JSONField(null=True)),
                ('time_taken', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronunciation_results', to='school_api.testsessionschool')),
            ],
        ),
    ]
