# Generated by Django 4.2.9 on 2024-06-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.TextField(null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_passed', models.BooleanField(default=False)),
                ('score', models.FloatField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('student_id', models.BigIntegerField()),
                ('model', models.CharField(max_length=255, null=True)),
                ('topic', models.CharField(max_length=500, null=True)),
                ('prompt_json', models.JSONField(null=True)),
                ('wait_time', models.FloatField(null=True)),
                ('token_usage', models.IntegerField(null=True)),
                ('graph_image', models.URLField(null=True)),
                ('word_count', models.IntegerField(null=True)),
                ('document', models.FileField(upload_to='task1_essay/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task 1 Essay',
                'verbose_name_plural': 'Task 1 Essays',
                'db_table': 'task1_essays',
            },
        ),
        migrations.CreateModel(
            name='Task2Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.TextField(null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_passed', models.BooleanField(default=False)),
                ('score', models.FloatField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('student_id', models.BigIntegerField()),
                ('model', models.CharField(max_length=255, null=True)),
                ('topic', models.CharField(max_length=500, null=True)),
                ('prompt_json', models.JSONField(null=True)),
                ('wait_time', models.FloatField(null=True)),
                ('token_usage', models.IntegerField(null=True)),
                ('word_count', models.IntegerField(null=True)),
                ('document', models.FileField(upload_to='task2_essay/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task 2 Essay',
                'verbose_name_plural': 'Task 2 Essays',
                'db_table': 'task2_essays',
            },
        ),
    ]
