# Generated by Django 4.2.9 on 2024-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gpt4-o', 'GPT-4 OpenAI'), ('mixtral', 'MIXTRAL')], default='gpt4-o', max_length=255)),
                ('temp', models.FloatField(default=0)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('system_text', models.TextField(null=True)),
            ],
        ),
    ]
