# Generated by Django 4.2.9 on 2024-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_checker', '0002_writingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingconfig',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT4-O'), ('gpt-4-turbo', 'GPT4-Turbo'), ('mixtral', 'MIXTRAL')], default='gpt4-o', max_length=255),
        ),
    ]
